smart_open library not found; falling back to local-filesystem-only
>> Synonyms load wordseg dict [/usr/lib/python2.7/site-packages/synonyms/data/vocab.txt] ... 
>> Synonyms on loading stopwords [/usr/lib/python2.7/site-packages/synonyms/data/stopwords.txt] ...
>> Synonyms on loading vectors [/usr/lib/python2.7/site-packages/synonyms/data/words.vector] ...
record ready
line = 2, 0 has 0, 1 has 1
Traceback (most recent call last):
  File "form_train_data_II.py", line 304, in form_train_data_redis
    out_row = [brand_name.encode("gbk"), his_name.encode("gbk"), brand_no, brand_no_his,
UnicodeEncodeError: 'gbk' codec can't encode character u'\u2022' in position 2: illegal multibyte sequence

line = 3, 0 has 0, 1 has 2
line = 4, 0 has 1, 1 has 2
line = 5, 0 has 1, 1 has 3
line = 6, 0 has 1, 1 has 4
line = 7, 0 has 1, 1 has 5
line = 8, 0 has 1, 1 has 6
line = 9, 0 has 1, 1 has 7
Traceback (most recent call last):
  File "form_train_data_II.py", line 301, in form_train_data_redis
    his_name = compare_unit["name"].decode("utf-8")
TypeError: 'NoneType' object has no attribute '__getitem__'

line = 10, 0 has 1, 1 has 8
line = 11, 0 has 1, 1 has 9
line = 12, 0 has 2, 1 has 9
line = 13, 0 has 2, 1 has 10
line = 14, 0 has 2, 1 has 11
line = 15, 0 has 2, 1 has 12
line = 16, 0 has 2, 1 has 13
line = 17, 0 has 2, 1 has 14
line = 18, 0 has 2, 1 has 15
Traceback (most recent call last):
  File "form_train_data_II.py", line 301, in form_train_data_redis
    his_name = compare_unit["name"].decode("utf-8")
TypeError: 'NoneType' object has no attribute '__getitem__'

line = 19, 0 has 2, 1 has 16
line = 20, 0 has 2, 1 has 17
line = 21, 0 has 2, 1 has 18
line = 22, 0 has 2, 1 has 19
line = 23, 0 has 2, 1 has 20
line = 24, 0 has 2, 1 has 21
line = 26, 0 has 2, 1 has 22
line = 27, 0 has 2, 1 has 23
line = 28, 0 has 2, 1 has 24
line = 29, 0 has 2, 1 has 25
line = 30, 0 has 2, 1 has 26
line = 31, 0 has 2, 1 has 27
Traceback (most recent call last):
  File "form_train_data_II.py", line 301, in form_train_data_redis
    his_name = compare_unit["name"].decode("utf-8")
TypeError: 'NoneType' object has no attribute '__getitem__'

line = 32, 0 has 2, 1 has 28
line = 33, 0 has 2, 1 has 29
line = 34, 0 has 2, 1 has 30
line = 35, 0 has 2, 1 has 31
line = 37, 0 has 2, 1 has 32
line = 38, 0 has 2, 1 has 33
Traceback (most recent call last):
  File "form_train_data_II.py", line 301, in form_train_data_redis
    his_name = compare_unit["name"].decode("utf-8")
TypeError: 'NoneType' object has no attribute '__getitem__'

line = 40, 0 has 2, 1 has 34
line = 41, 0 has 2, 1 has 35
line = 42, 0 has 3, 1 has 35
line = 43, 0 has 3, 1 has 36
line = 44, 0 has 3, 1 has 37
line = 45, 0 has 3, 1 has 38
line = 46, 0 has 3, 1 has 39
Traceback (most recent call last):
  File "form_train_data_II.py", line 301, in form_train_data_redis
    his_name = compare_unit["name"].decode("utf-8")
TypeError: 'NoneType' object has no attribute '__getitem__'

line = 47, 0 has 3, 1 has 40
line = 48, 0 has 3, 1 has 41
line = 49, 0 has 4, 1 has 41
line = 50, 0 has 4, 1 has 42
line = 51, 0 has 4, 1 has 43
line = 52, 0 has 5, 1 has 43
Traceback (most recent call last):
  File "form_train_data_II.py", line 301, in form_train_data_redis
    his_name = compare_unit["name"].decode("utf-8")
TypeError: 'NoneType' object has no attribute '__getitem__'

line = 53, 0 has 5, 1 has 44
Traceback (most recent call last):
  File "form_train_data_II.py", line 301, in form_train_data_redis
    his_name = compare_unit["name"].decode("utf-8")
TypeError: 'NoneType' object has no attribute '__getitem__'

line = 54, 0 has 5, 1 has 45
Traceback (most recent call last):
  File "form_train_data_II.py", line 301, in form_train_data_redis
    his_name = compare_unit["name"].decode("utf-8")
TypeError: 'NoneType' object has no attribute '__getitem__'

line = 55, 0 has 5, 1 has 46
line = 56, 0 has 6, 1 has 46
Traceback (most recent call last):
  File "form_train_data_II.py", line 301, in form_train_data_redis
    his_name = compare_unit["name"].decode("utf-8")
TypeError: 'NoneType' object has no attribute '__getitem__'

line = 57, 0 has 6, 1 has 47
line = 58, 0 has 7, 1 has 47
line = 59, 0 has 7, 1 has 48
line = 60, 0 has 8, 1 has 48
line = 61, 0 has 9, 1 has 48
Traceback (most recent call last):
  File "form_train_data_II.py", line 301, in form_train_data_redis
    his_name = compare_unit["name"].decode("utf-8")
TypeError: 'NoneType' object has no attribute '__getitem__'

line = 62, 0 has 9, 1 has 49
line = 63, 0 has 9, 1 has 50
line = 64, 0 has 9, 1 has 51
line = 65, 0 has 9, 1 has 52
line = 66, 0 has 10, 1 has 52
line = 67, 0 has 10, 1 has 53
line = 68, 0 has 10, 1 has 54
line = 69, 0 has 10, 1 has 55
line = 70, 0 has 10, 1 has 56
line = 71, 0 has 10, 1 has 57
line = 72, 0 has 10, 1 has 58
line = 73, 0 has 10, 1 has 59
line = 74, 0 has 11, 1 has 59
line = 75, 0 has 12, 1 has 59
line = 76, 0 has 13, 1 has 59
Traceback (most recent call last):
  File "form_train_data_II.py", line 301, in form_train_data_redis
    his_name = compare_unit["name"].decode("utf-8")
TypeError: 'NoneType' object has no attribute '__getitem__'

line = 77, 0 has 13, 1 has 60
line = 78, 0 has 13, 1 has 61
line = 79, 0 has 13, 1 has 62
Traceback (most recent call last):
  File "form_train_data_II.py", line 301, in form_train_data_redis
    if compare_unit == None:
TypeError: 'NoneType' object has no attribute '__getitem__'

line = 80, 0 has 13, 1 has 63
line = 81, 0 has 13, 1 has 64
line = 82, 0 has 13, 1 has 65
line = 83, 0 has 14, 1 has 65
line = 84, 0 has 14, 1 has 66
line = 85, 0 has 14, 1 has 67
line = 86, 0 has 14, 1 has 68
Traceback (most recent call last):
  File "form_train_data_II.py", line 301, in form_train_data_redis
    if compare_unit == None:
TypeError: 'NoneType' object has no attribute '__getitem__'

line = 87, 0 has 14, 1 has 69
line = 88, 0 has 14, 1 has 70
line = 89, 0 has 14, 1 has 71
